### ISSUE TITLE
Memory leak on serving a file

### ISSUE THREAD

**Issue by afuriza** [afuriza/kyoukai_framework#5]
MimeTypes.LoadFromFile(MimeTypesFile);

This line caused memory leak when we load mimetypes from file every single file request, temporary Kyoukai changed it load mimetypes when filename of mimetypes are different.

I have an idea to create TFPMimeTypes every request, but it causes huge CPU load.

I don't have any idea yet to fix this.

**Comment by lainz** [comment]
Hi, this looks promising, because we can embedd it on an existing application. It will work for an existing GUI application as well?

**Comment by afuriza** [comment]
Yeah, but you need to use Thread to start with TKyServer in Kyoukai.Standard.HTTPServer, you can't use standard Routes and KyoukaiApp, I'll commit example later.

**Comment by lainz** [comment]
Thanks!

**Comment by afuriza** [comment]
Hi, @lainz, I have an update with embedding server into the application, #8 there's problem to stop the server. So, it works, but you need to kill whole application to kill the server.

**Comment by lainz** [comment]
Thankyou. I will try to test it soon. I'm thinking on using your library as a replacement of Brook Framework. The app where I need to use it uses JSON data (with POST and GET endpoints) to send / receive from an Android app, and it will be good to include the server in the main program to share database connections and stuff like that.

**Comment by afuriza** [comment]
#3161a26

**Comment by afuriza** [comment]
Commit [#b02da75de5f5a8972cde926367f016452181518c](https://github.com/afuriza/kyoukai_framework/commit/b02da75de5f5a8972cde926367f016452181518c), marked RTTI method in webmodule as the culprit, moved to webhandle.
