### ISSUE TITLE
Post, Get Parameters?

### ISSUE THREAD

**Issue by lainz** [afuriza/kyoukai_framework#6]
Hi, this supports Post, and Get Parameters?

like get parameters localhost/?id=1234&id2=5678

selecting each parameter, for example from a TStringList.

And post, like sending to the server a string, that can be readed in the corresponding method?

**Comment by afuriza** [comment]
You can using _get['paramname] or _post['paramname'] to read post and get parameters.

- sorry for my bad english

**Comment by afuriza** [comment]
For an example
- like get parameters localhost/?id=1234&id2=5678
```
unit main_controller;

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils,
  Kyoukai.Standard.WebRouter,
  Kyoukai.Standard.WebModule;

type
  THome = class(TKyModule)
  published
    procedure MainHandle;
  end;

implementation

procedure THome.MainHandle;
begin
  _echo('ID: '+_GET['id']+'<br>');
  _echo('ID 2: '+_GET['id2']+'<br>');
end;

initialization
Routes['main'] := THome;
end.
```

**Comment by lainz** [comment]
Thankyou!
Looks really good =)

**Comment by afuriza** [comment]
Thank you!

Btw, I love your Pascal's repo.

**Comment by lainz** [comment]
Thankyou, this looks very promising, keep going!
